package yyd.yun.dao;


import org.apache.ibatis.annotations.Param;

import yyd.yun.beans.Operator;


public interface OperatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_operator
     *
     * @mbg.generated Mon Jun 26 19:47:23 CST 2017
     */
    int deleteByPrimaryKey(@Param("id") Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_operator
     *
     * @mbg.generated Mon Jun 26 19:47:23 CST 2017
     */
    int insert(Operator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_operator
     *
     * @mbg.generated Mon Jun 26 19:47:23 CST 2017
     */
    int insertSelective(Operator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_operator
     *
     * @mbg.generated Mon Jun 26 19:47:23 CST 2017
     */
    Operator selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_operator
     *
     * @mbg.generated Mon Jun 26 19:47:23 CST 2017
     */
    int updateByPrimaryKeySelective(Operator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_operator
     *
     * @mbg.generated Mon Jun 26 19:47:23 CST 2017
     */
    int updateByPrimaryKey(Operator record);

	Operator selectByUserName(@Param("username") String username);
	
	int delRoleOperatorRelationship(@Param("operatorId") Integer operatorId);
	
	int delRoleIdAndOperatorId(@Param("operatorId") Integer operatorId,@Param("roleId") Integer roleId);
	
	
}