package yyd.yun.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import yyd.yun.beans.Role;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_role
     *
     * @mbg.generated Mon Jun 26 19:47:23 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_role
     *
     * @mbg.generated Mon Jun 26 19:47:23 CST 2017
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_role
     *
     * @mbg.generated Mon Jun 26 19:47:23 CST 2017
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_role
     *
     * @mbg.generated Mon Jun 26 19:47:23 CST 2017
     */
    Role selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_role
     *
     * @mbg.generated Mon Jun 26 19:47:23 CST 2017
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_role
     *
     * @mbg.generated Mon Jun 26 19:47:23 CST 2017
     */
    int updateByPrimaryKey(Role record);

    
	List<Role> queryRoleByUserName(@Param("username") String username);
	
	
	List<Role> queryRoleByUserId(@Param("id") Integer id);
	
	
	List<Role> selectRole();
	
	
	int insertRoleOperator(@Param("roleId")Integer roleId,@Param("operatorId")Integer operatorId);
	
	//新增角色权限
	int insertRolePermission(@Param("roleId")Integer roleId,@Param("permissionId")Integer permissionId);
	
}