package yyd.yun.beans;

import java.io.Serializable;

public class Permission implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_permission.id
     *
     * @mbg.generated Mon Jun 26 19:47:23 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_permission.permission_name
     *
     * @mbg.generated Mon Jun 26 19:47:23 CST 2017
     */
    private String permissionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_permission.permission
     *
     * @mbg.generated Mon Jun 26 19:47:23 CST 2017
     */
    private String permission;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_permission.id
     *
     * @return the value of pms_permission.id
     *
     * @mbg.generated Mon Jun 26 19:47:23 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_permission.id
     *
     * @param id the value for pms_permission.id
     *
     * @mbg.generated Mon Jun 26 19:47:23 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_permission.permission_name
     *
     * @return the value of pms_permission.permission_name
     *
     * @mbg.generated Mon Jun 26 19:47:23 CST 2017
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_permission.permission_name
     *
     * @param permissionName the value for pms_permission.permission_name
     *
     * @mbg.generated Mon Jun 26 19:47:23 CST 2017
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName == null ? null : permissionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_permission.permission
     *
     * @return the value of pms_permission.permission
     *
     * @mbg.generated Mon Jun 26 19:47:23 CST 2017
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_permission.permission
     *
     * @param permission the value for pms_permission.permission
     *
     * @mbg.generated Mon Jun 26 19:47:23 CST 2017
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

	@Override
	public String toString() {
		return "Permission [id=" + id + ", permissionName=" + permissionName + ", permission=" + permission + "]";
	}
    
}