package yyd.yun.beans;

import java.io.Serializable;

public class Role implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_role.id
     *
     * @mbg.generated Mon Jun 26 19:47:23 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_role.role_name
     *
     * @mbg.generated Mon Jun 26 19:47:23 CST 2017
     */
    private String roleName;

    public Role(Integer id, String roleName) {
		super();
		this.id = id;
		this.roleName = roleName;
	}
    
    public Role() {
		// TODO Auto-generated constructor stub
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_role.id
     *
     * @return the value of pms_role.id
     *
     * @mbg.generated Mon Jun 26 19:47:23 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_role.id
     *
     * @param id the value for pms_role.id
     *
     * @mbg.generated Mon Jun 26 19:47:23 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_role.role_name
     *
     * @return the value of pms_role.role_name
     *
     * @mbg.generated Mon Jun 26 19:47:23 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_role.role_name
     *
     * @param roleName the value for pms_role.role_name
     *
     * @mbg.generated Mon Jun 26 19:47:23 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }
}